src/containers/SubtopicPage/SubtopicPage.js, src/containers/SubtopicPage/SubtopicPageHelper.js, src/containers/SubtopicPage/components/ModeBox.js, src/containers/SubtopicPage/components/SubtopicBox.js, src/global/const.js
integrate get subtopic name with topic name
ใน modeBox หลังกดจะส่ง subtopic_id, mode, difficulty ไปให้หน้าเกม ปอลอ คิดว่าต้องกลับมาแก้ pathname
=> C-22/Integrate-API-for-get-subtopic

src/App.js, src/components/GameContent.js, src/components/ProblemBox.js, src/containers/PracticeGame/PracticeGame.js, src/containers/PracticeGame/PracticeGameHelper.js, src/containers/SubtopicPage/SubtopicPage.js, src/containers/SubtopicPage/components/ModeBox.js, src/containers/SubtopicPage/components/SubtopicBox.js
integrate get problem แต่ว่า mock user_id ไว้ ไว้มาเชื่อมตอน sprint 2
แต่ตัวโจทย์ยังเพี้ยนๆ เพราะไม่ได้ handle ว่าให้ตัวเลขมันยกกำลังเมื่อไหร่ มันจะออกตาม text ที่ได้รับเลย
=> C-15/integrate get problem

src/App.js, src/components/TextField.js, src/containers/EditUsernamePage/EditUsernamePage.js, src/containers/ProfilePage/ProfilePage.js
เพิ่มหน้า edit username กับทำให้ upload รูปได้
ปล. แต่ยังไม่ชัวว่ารูปที่ upload ไปจะเข้า database แล้วเอ๋อมั้ย ต้องลองนะ555555555
=> C2-03/upload-image-and-edit-username

src/App.js
ถ้า token หมดอายุ หรือใด ๆ ก็ตามที่ทำให้ token เหมือนจะหมดอายุ เช่น log out จาก mcv ซัมติง ให้เด้งกลับไปหน้า log in
=> [C2-01/C2-16] fixed expired token

src/App.js, src/components/Leaderboard/TabContent.js, src/containers/Homepage/Homepage.js, src/containers/Homepage/HomepageHelper.js, src/containers/OAuthRedirectPage/OAuthRedirectPage.js
เราไม่แน่ใจว่าตอนรับ user_id เรารับจากหน้า app.js แบบนี้ได้เลยป่าวอะ
```
<PrivateRoute exact path="/homepage" getUserData={getUserData}>
<Homepage user_id={user_id}/>
</PrivateRoute>
```
ใส่ loading ในหน้า oauth ไม่งั้นตอนก่อนมัน redirect เข้า homepage เป็นหน้าว่างๆขาวๆอะ
=> C2-24/integrate-get-leader-board

src/containers/ChallengeGame/ChallengeGame.js, src/containers/ChallengeGame/ChallengeGameHelper.js
integrate get problem หน้า challenge จาก challenge_id & index
แต่ว่ายังไม่ได้ handle เรื่องกดข้าม ฝากคน integrate check answer ดูเรื่องนี้นะ เพราะมันต้องยิงส่งคำตอบว่างไปด้วยต่างๆ แล้วก็ฝากให้มัน get info ใหม่ทุกครั้งด้วยนะ
=> C3-21/integrate-get-problem-by-challenge-id-and-index

src/components/AnswerModal.js, src/components/Modal.js, src/containers/QuizGame/QuizGame.js
ทำให้เวลาหยุดหลังกดตรวจ กับให้กดพื้นหลังไม่ได้
=> fixed: stop time and make overlay not clickable

src/App.js, src/index.js, src/route/PrivateRoute.js
ทำให้ทุกครั้งที่เปลี่ยนหน้าจะเรียก getUseData 1 ครั้งละ
แต่ว่า ต้องใส่ `getUserData={getUserData}` ให้**ทุก privateRoute** นะ
=> fixed: edit privateRoute to call getUserData only once when change path

src/components/ConfirmResultModal.js
วิธีใช้เหมือน comfirmResultModal ปกติ แค่เพิ่ม pin มา (สามารถไม่ส่ง pin ไปได้ จะเป็น comfirmResultModal ปกติ)
```
<ConfirmResultModal
isShowing={isShowing}
toggle={toggle}
success={true}
pin="123456"
success_description="ขอบคุณสำหรับความใส่ใจ :)"
fail_description="ล้มเหลว กรุณาส่งปัญหานี้ใหม่อีกครั้ง"
/>
```
=> C4-03/Create-and-join-group-modal

src/containers/JoinGroupPage/JoinGroupPage.js, src/containers/JoinGroupPage/JoinGroupPageHelper.js, src/containers/WaitingRoomPage/WaitingRoomPage.js
integrate หน้า join group
++ ส่ง group id ไปให้หน้า waiting room
++ ใส่ error message
=> C4-22/integrate join group

src/containers/WaitingRoomPage/WaitingRoomPage.js, src/containers/WaitingRoomPage/WaitingRoomPageHelper.js
integrate หน้า waiting room
หน้านี้จะ get data ตลอดเวลา update คนในกลุ่ม
=> C4-24/integrate get all group members

src/components/Dropdown/Dropdown.js, src/containers/CreateGroupPage/CreateGroupPage.js, src/containers/CreateGroupPage/CreateGroupPageHelper.js
integrate หน้า create group เอาข้อมูล subjects topic subtopics difficulty มาแสดง
=> C4-23/integrate get group data

src/containers/GroupGamePage/GroupGamePage.js, src/containers/GroupGamePage/GroupGamePageHelper.js, src/containers/WaitingRoomPage/WaitingRoomPage.js, src/containers/WaitingRoomPage/WaitingRoomPageHelper.js
integrate หน้า waiting room ตอนกดปุ่ม start ให้ไปหน้า group game
=> C4-34/integrate-gen-problem-when-group-start

src/containers/ProfilePage/ProfilePage.js
แก้หน้า profile ให้ hover แล้วคนที่มี profile image ภาพไม่หาย
ก่อนหน้านี้ภาพมันจะหายไปตอน hover ขึ้นแต่ icon change image
=> fixed: edit when hover on profile picture

src/components/ConfirmResultModal.js, src/components/Modal.js, src/containers/CreateGroupPage/CreateGroupPage.js, src/containers/CreateGroupPage/CreateGroupPageHelper.js, src/containers/GroupGamePage/GroupGamePage.js, src/containers/GroupGamePage/GroupGamePageHelper.js, src/containers/JoinGroupPage/JoinGroupPage.js, src/containers/JoinGroupPage/JoinGroupPageHelper.js, src/containers/WaitingRoomPage/WaitingRoomPage.js
เติม confirmResultModal ให้หน้า Create group กับ Join group
กับเพิ่ม pin ไว้หน้า Waiting Room
=> fixed: add confirmResultModal for CreateGroup and JoinGroup

src/containers/AllChallengePage/AllChallengePage.js
ทำให้ตอนเข้าหน้า all challenge จะอ่าน their turn challenge เลย ให้แค่ new challenge ที่ขึ้นสี
=> fixed: add readTheirTurnChallenge for allChallenge page

.gitignore, src/containers/LoginPage/LoginPage.js, src/ip.js
แก้ login ให้ใช้ ตัวแปรตาม env
file ที่ต้องแก้ ignore ไว้ เพื่อนต้องไปดูที่ notion นะ
=> Add .env to handle env variable

package.json, src/components/Answer/AnswertHelper.js, src/containers/GroupGamePage/GroupGamePage.js, src/containers/GroupGamePage/GroupGamePageHelper.js, src/containers/GroupGamePage/components/NumberOfAnswer.js, src/containers/GroupGamePage/components/PointBox.js, src/containers/GroupResultPage/GroupResultPage.js, src/containers/GroupResultPage/GroupResultPageHelper.js, src/containers/JoinGroupPage/JoinGroupPage.js, src/containers/JoinGroupPage/JoinGroupPageHelper.js, src/containers/WaitingRoomPage/WaitingRoomPage.js, src/containers/WaitingRoomPage/WaitingRoomPageHelper.js
เอา ServerSentEvent มาใช้ใน groupGame ตั้งแต่หน้า waitingRoom จนถึงหน้า GroupResult
รวมๆคือ สามารถ getAllMember ใหม่ทุกครั้งที่ member มีการเปลี่ยนแปลง ได้แล้ว
ถ้าเจ้าของกดเริ่มเกมใน waitingRoom ทุกคนในกลุ่มจะเปลี่ยนไปหน้า groupGame เลย
ถ้าลบกลุ่มจากหน้า waitingRoom จะไปหน้า errorPage แต่ถ้าจากหน้า groupResult จะไปหน้า homepage
แต่ในหน้า groupResult ถ้ากด เริ่มเล่นใหม่ ตอนนี้จะพังอยู่ backend crashed ไปเลย ไม่รู้ว่าทำไม **--> ไม่พังแล้วจ้า**
ส่วนในหน้า groupGame เจ้าของกลุ่มต้องกด เริ่มข้อต่อไป เพื่อให้ทุกคนในกลุ่มเปลี่ยนเป็นข้อต่อไปตาม แต่หน้านี้ต้องฝากซาทำต่อ เพราะความจริงมันต้องแสดงเฉลยก่อน แล้วทิ้งไว้แปปนึง(ซัก 10-15 วิ น่าจะพอ) แล้วค่อยเปลี่ยนไปหน้าต่อไป หรือไปหน้า result ซึ่งตอนนี้มันยังไม่เชื่อมส่วนเช็คคำตอบส่วนเฉลย เราเลยทำให้มันไปข้อต่อไปเลย …
=> using useServerSentEvent for groupGame

src/components/Button.js, src/components/Leaderboard/TabContent.js, src/components/Navbar.js, src/components/NumberInputSpinner.js, src/containers/CreateGroupPage/CreateGroupPage.js, src/containers/CreateGroupPage/CreateGroupPageHelper.js, src/containers/Homepage/components/GroupPanel.js, src/containers/Page.js
สิ่งที่แก้
- **max-height** for all buttons: **48px;**
- leaderboard -> **min-height** for userInfo **40px;**
- sticky navbar -> **navbar - position: fixed, page - margin-top: 54px**
before:
after:
=> [FIXED] for safari

src/App.js, src/components/HintItem.js, src/components/LevelUpModal.js, src/containers/AllChallengePage/AllChallengePage.js, src/containers/ChallengeGamePage/ChallengeGamePage.js, src/containers/ChallengeResultPage/ChallengeResultPage.js, src/containers/PracticeAnswer/PracticeAnswer.js, src/containers/PracticeGamePage/PracticeGamePage.js, src/containers/PracticeGamePage/PracticeGamePageHelper.js, src/containers/QuizGamePage/QuizGamePage.js, src/containers/QuizGamePage/QuizGamePageHelper.js, src/containers/QuizGamePage/components/HeadlineItem.js, src/containers/QuizResultPage/QuizResultPage.js
integrate level up กับ rank up modal
practice --> practice answer
quiz --> quiz result
challenge --> ตอนเล่นเสร็จแล้วกลับมาหน้า all challenge
=> Integrate level and rank up

src/containers/ProfilePage/ProfilePage.js, src/containers/ProfilePage/ProfilePageHelper.js, src/route/PrivateRoute.js
=> Change profile image

src/components/Answer/AnswerRadioChoice.js, src/components/Answer/AnswertHelper.js, src/components/AnswerModal.js, src/components/HandleText.js, src/components/HintItem.js, src/components/Leaderboard/TabContent.js, src/components/ProblemBox.js, src/components/RadioButton.js, src/containers/PracticeAnswer/PracticeAnswer.js, src/containers/PracticeAnswer/components/Solution.js, src/global/const.js, src/global/utils.js
- **แก้เรื่องภาษาไทยในโจทย์กับ hint**
- **แก้เรื่องเครื่องหมายคูณ**
=> Handle-math-text

src/components/AnswerModal.js, src/components/HandleText.js, src/containers/ProfilePage/ProfilePage.js, src/containers/ProfilePage/components/Item.js
เพิ่มสีพื้นหลังใน freeze, double ในหน้า profile
fixed answer modal thai text for math
แก้สำหรับวิชาเลข: อันนี้มันดักเฉพาะอักษรไทยนะ ถ้าเป็นตัวอิ้งหรือตัวเลข มันจับยัดใส่ math-text เน้อ
Before:
After:
=> [Fixed] Handle-Math-Text

src/containers/ChallengeGamePage/ChallengeGamePage.js
ไม่คอลขอข้อใหม่ ตอนถึงข้อสุดท้าย
=> fix: Remove calling API in onExit

src/containers/AllChallengesPage/AllChallengesPage.js, src/containers/ChallengeGamePage/ChallengeGamePage.js, src/containers/QuizGamePage/QuizGamePage.js
เพิ่ม answer modal loading ให้หน้า challenge, quiz
ส่วนหน้า practice มีอยู่แล้ว
=> add answer_modal_loading for challenge and quiz

src/containers/ProfilePage/ProfilePage.js
ให้เวลาถึงจะเปลี่ยนรูปไม่สำเร็จเวลากดยืนยันก็จะ refresh หน้า เพราะตอนนี้ถ้าไม่ refresh จะกดเปลี่ยนรูปไม่ได้
=> edit to refresh even when change image unsuccess

src/components/Answer/AnswerSelectOne.js, src/components/Button.js, src/components/Dropdown.js, src/components/ExitModal.js, src/components/HandleText.js, src/components/HintItem.js, src/components/ItemBox.js, src/components/ItemCard.js, src/components/NumberInputSpinner.js, src/components/RadioButton.js, src/containers/AllChallengesPage/components/ChallengeBox.js, src/containers/AllModeChallengesPage/AllModeChallengesPage.js, src/containers/AllModeChallengesPage/components/ChallengeBox.js, src/containers/Homepage/components/AchievementPanel.js, src/containers/Homepage/components/SubjectCard.js, src/containers/PracticeAnswer/PracticeAnswer.js, src/containers/PracticeGamePage/PracticeGamePage.js, src/containers/ProfilePage/ProfilePage.js, src/containers/ProfilePage/components/Item.js, src/containers/TopicPage/components/TopicBox.js
**display text**: แก้เรื่องเว้นวรรค
**cursor**:
หน้า profile
- รูป profile
- icon edit username
- item -> freeze + double
หน้า practice answer
- icon ">" for solution
หน้า homepage
- subject card
- achievement box -> "..."
หน้า all challenge
- แบ่ง mode: challenge box -> for รอบของคุณ, ผลลัพธ์
- รวมทุก mode: ใส่ทุกกล่อง
component
- exit-modal
- item card -> พวก hint, skip ไรงี้ในหน้าเกม
- button -> all "pointer" except disabled "default"
- item box -> topic box
- hint modal -> exit icon
- radio button
- dropdown
- NumberInputSpinner
=> add-cursor

src/components/HandleText.js, src/components/RadioButton.js, src/containers/QuizGamePage/QuizGamePage.js, src/containers/QuizGamePage/QuizGamePageHelper.js, src/containers/QuizGamePage/components/HeadlineItem.js
ทำให้มันไม่มี delay หลังกดใช้ไอเทม ของ quizGame
https://user-images.githubusercontent.com/42530370/108020914-0942cf00-7050-11eb-8872-adbecdcbb6db.mov
=> fixed delay when use item for quizGame

src/containers/SubtopicPage/components/ModeBox.js
เร็วช้า ไปปรับที่ บรรทัด 70 ของ subtopic -> component -> modebox
`whileTap={{ x: -(box_width + 16), right: 0, transition: {duration: 0.5} }}`
=> modebox-slide-on-click

package-lock.json, package.json, src/containers/ProfilePage/ProfilePage.js, src/containers/ProfilePage/ProfilePageHelper.js
resize รูปก่อน upload ให้ขนาดไม่เกิน 100 KB
=> fixed: change profile image

src/containers/GroupGamePage/GroupGamePage.js
=> fixed: group game answer modal loading

src/containers/GroupGamePage/GroupGamePage.js, src/containers/WaitingRoomPage/WaitingRoomPage.js
แก้อีกรอบ ให้มัน unsub ตอนเปลี่ยนหน้า groupGame ละเข้าหน้าแล้วค่อย sub ใหม่
=> fixed: group game

src/containers/GroupGamePage/GroupGamePage.js, src/containers/GroupGamePage/GroupGamePageHelper.js
เพิ่มให้ถ้าไม่ใช่เจ้าของห้อง ถ้ากดปิดระหว่างเกม ก็จะ leaveGroup, unsub ละกลับไปหน้า homepage
=> fixed: add leaveGroup for groupGame player

src/containers/ShopPage/ShopPage.js, src/containers/ShopPage/ShopPageHelper.js
=> add error msg for buy item

src/components/Leaderboard/TabContent.js
เพิ่ม cursor ให้ leaderboard ตรงกล่องชื่อ เพราะมันสามารถกดได้ (กดแล้วเป็น modal)
=> add cursor to leaderboard -> click display modal

src/containers/AchievementPage/components/AllAchievements.js
=> fix: overflow hidden
